import Head from "next/head";
import { AiFillLinkedin } from "react-icons/ai";
import { FaGithub } from 'react-icons/fa';
import Image from "next/image";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {useState} from "react";
import { useRef } from 'react';

export default function Home() {
  const aboutMeRef = useRef(null);
  const projectRef = useRef(null);
  const [darkMode, setDarkMode] = useState(false)
  return (
    <div className={darkMode ? "dark bg-gray-800" : "bg-gray-100"}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
     
        <nav className="py-10 mb-12 flex justify-between dark:text-white w-full border-b-2 border-red-500">
          <h1 className="font-burtons text-xl">Al Azmine</h1>
          <ul className="flex items-center">
            <li>
              <BsFillMoonStarsFill
                onClick={() => setDarkMode(!darkMode)}
                className=" cursor-pointer text-2xl"
              />
            </li>
            <li>
                <a className = "ml-8" href="#">Home</a>
              </li>
              <li>
              <a className = "ml-8"  href="#" onClick={() => aboutMeRef.current.scrollIntoView({ behavior: 'smooth' })}> About</a>
              </li>
              <li>
                <a  className = "ml-8" onClick={() => projectRef.current.scrollIntoView({behavior: 'smooth'})}  href="#">Projects</a>
              </li>
              <li>
                <a  className = "ml-8" href="#">Contact</a>
              </li>
            </ul>
        </nav>
        <section ref={aboutMeRef} className="min-h-screen  my-0">
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-red-600 font-medium md:text-6xl">Hello, I'm Al Azmine</h2>
            <h3 className="text-2xl py-2 md:text-3xl text-red-300" >Software Engineer.</h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto" >
              Recent graduate looking for a full-time job opportunity within the Software Engineering field.
              As a recent graduate with a Bachelor of Science in Computer Science from California State University, Northridge. While my professional journey has yet to begin, I am determined to change that. I have decided to pursue a Master's Degree in Software Engineering at CSUN, starting in the spring of 2024. I believe my
              academic background has equipped me with a robust foundation in computer science and proficiency in programming languages such as Python, Java, HTML, C++, and Javascript. I
              have confidence that my solid foundation in these languages and my problem-solving skills will allow me to adapt swiftly and make meaningful contributions to projects. I want to make the
              most of the opportunity and further my career. I am excited about working in a challenging and collaborative environment where I can apply my knowledge to real-world scenarios and grow as
            a software engineer
              Contact me below.
            </p>
          </div> 
          </section>
          <h2 className = "text-center">About Me</h2>
          <div className="flex justify-center">
  <section className="Edu flex flex-col text-center border border-gray-500 max-w-md rounded-xl  mr-5">
    <h2 className="py-2 font-medium ">Education</h2>
    <div className="wrap">
        <small>B.S, Computer Science</small>
        <br/>
        <small>2018 - 2023</small>
       
    </div>
  </section>

  <section className="text-center font-medium max-w-md flex">
    <div className="shadow-lg p-5 rounded-xl my-5 border border-gray-500">
      <h2>Skills</h2>
      <p>Java</p>
      <p>Python</p>
      <p>C++</p>
      <p>JavaScript</p>
    </div>
  </section>
</div>

          <section ref= {projectRef} className=" my-0" >
          <h4 className="text-3xl py-1 text-center " > Projects I have done</h4>
            <div className = "text-center shadow-lg p-10 rounded-xl my-10  border border-gray-500">
            <h3>Multi Media Design</h3>
            <p> Built an automation script using Python, that automates 4 manual positions in a matter of seconds Python code reads proprietary data from Baselight and Flame machines to calculate the filesystem locations of frames. All requests are saved to a database and can be used for data analysis and worker efficiency. Exports are essential CSV files to XLS files with timecode and thumbnail preview that can be uploaded to Frame.IO and Shotgrid  </p>
            <h4></h4>
            <p className="text-gray-800 py-1">Picture</p>
            <p className="text-gray-800 py-1"> Link</p>
            
          </div>
          <div className = "text-center shadow-lg p-10 rounded-xl my-10  border border-gray-500">
            <h3>Trader Joe's Recipie Hub</h3>
            <p> Built an automation script using Python, that automates 4 manual positions in a matter of seconds Python code reads proprietary data from Baselight and Flame machines to calculate the filesystem locations of frames. All requests are saved to a database and can be used for data analysis and worker efficiency. Exports are essential CSV files to XLS files with timecode and thumbnail preview that can be uploaded to Frame.IO and Shotgrid  </p>
            <h4></h4>
            <p className="text-gray-800 py-1">Picture</p>
            <p className="text-gray-800 py-1"> Crazy Poker</p>
           
          </div>
        </section>
        
       
        <section>
          <div>
            <h3> Portfolio</h3>
          </div>
        <div>
          <div>
            <h3>Contact</h3>
            <h2> Al Azmine</h2>
            <h2>Email: aazmine594@gmail.com</h2>
            <h2>Phone Number: (310)-529-1439</h2>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="#">
              <AiFillLinkedin />
            </a>
            <a href="#">
              <FaGithub />
            </a>
            
          </div>
         
          </div>
        </div>
        </section>
      </main>
    </div>
  );
}
